"""Catalog of /seo commands exposed by the Claude SEO skill.

Single source of truth for the frontend command list. Each entry mirrors the
SKILL.md Quick Reference table at ~/.claude/skills/seo/SKILL.md.
"""

COMMANDS = [
    {"key": "audit", "label": "Full Site Audit",
     "one_liner": "Full website audit with parallel sub-agents (technical, content, schema, performance, GEO, SXO).",
     "agents": ["seo-technical", "seo-content", "seo-schema", "seo-sitemap",
                "seo-performance", "seo-visual", "seo-geo", "seo-sxo"],
     "icon": "globe"},
    {"key": "page", "label": "Single Page Analysis",
     "one_liner": "Deep single-page SEO: on-page, content, meta, schema, images, performance.",
     "agents": ["seo-content", "seo-schema", "seo-visual"], "icon": "file"},
    {"key": "technical", "label": "Technical SEO",
     "one_liner": "Crawlability, indexability, robots.txt, Core Web Vitals, security headers, JS rendering.",
     "agents": ["seo-technical"], "icon": "wrench"},
    {"key": "content", "label": "Content Quality (E-E-A-T)",
     "one_liner": "E-E-A-T assessment, readability, thin content, AI citation readiness.",
     "agents": ["seo-content"], "icon": "book"},
    {"key": "schema", "label": "Schema / Structured Data",
     "one_liner": "Detect, validate, and generate Schema.org JSON-LD markup.",
     "agents": ["seo-schema"], "icon": "code"},
    {"key": "sitemap", "label": "Sitemap Analysis",
     "one_liner": "Analyze existing XML sitemap or generate a new one with industry templates.",
     "agents": ["seo-sitemap"], "icon": "map"},
    {"key": "images", "label": "Image SEO",
     "one_liner": "Alt text, file sizes, formats, responsive images, lazy loading, CLS prevention.",
     "agents": ["seo-visual"], "icon": "image"},
    {"key": "geo", "label": "GEO / AI Search Readiness",
     "one_liner": "Optimize for AI Overviews, ChatGPT, Perplexity. Citability, llms.txt, AI crawler access.",
     "agents": ["seo-geo"], "icon": "sparkles"},
    {"key": "local", "label": "Local SEO",
     "one_liner": "Google Business Profile, NAP consistency, citations, reviews, map pack.",
     "agents": ["seo-local", "seo-maps"], "icon": "pin"},
    {"key": "backlinks", "label": "Backlink Profile",
     "one_liner": "Referring domains, anchor text, toxic links, DA/PA (free APIs: Moz, Bing, Common Crawl).",
     "agents": ["seo-backlinks"], "icon": "link"},
    {"key": "hreflang", "label": "International / hreflang",
     "one_liner": "Multi-language and multi-region SEO audit. Validates hreflang tags and locale targeting.",
     "agents": ["seo-technical"], "icon": "flag"},
    {"key": "sxo", "label": "Search Experience Optimization",
     "one_liner": "Reads SERPs backwards to detect page-type mismatch and persona fit.",
     "agents": ["seo-sxo"], "icon": "users"},
    {"key": "ecommerce", "label": "E-commerce SEO",
     "one_liner": "Product schema, marketplace intel (Google Shopping, Amazon), pricing analysis.",
     "agents": ["seo-ecommerce"], "icon": "cart"},
    {"key": "drift", "label": "SEO Drift Monitoring",
     "one_liner": "Capture SEO baseline and detect regressions over time (git for SEO).",
     "agents": ["seo-drift"], "icon": "clock"},
    {"key": "cluster", "label": "Topic Clustering",
     "one_liner": "SERP-based semantic clustering for content architecture (hub-and-spoke planning).",
     "agents": ["seo-cluster"], "icon": "network"},
    {"key": "plan", "label": "Strategic SEO Plan",
     "one_liner": "Industry-specific SEO strategy, content calendar, site architecture, roadmap.",
     "agents": ["seo-plan"], "icon": "lightbulb"},
]

AGENTS = [
    {"id": "orchestrator", "label": "Orchestrator",
     "desc": "Reads SKILL.md, detects business type, delegates to sub-agents in parallel.",
     "color": "#b8860b"},
    {"id": "seo-technical", "label": "Technical",
     "desc": "Crawlability, indexability, robots.txt, security headers, Core Web Vitals.",
     "color": "#2d6a4f"},
    {"id": "seo-content", "label": "Content",
     "desc": "E-E-A-T, readability, thin content, AI citation readiness.",
     "color": "#1e3a5f"},
    {"id": "seo-schema", "label": "Schema",
     "desc": "Detect, validate, generate Schema.org JSON-LD markup.",
     "color": "#7c3aed"},
    {"id": "seo-sitemap", "label": "Sitemap",
     "desc": "XML sitemap structure, coverage, quality gates, missing pages.",
     "color": "#0891b2"},
    {"id": "seo-performance", "label": "Performance",
     "desc": "LCP, INP, CLS measurements via Lighthouse / CrUX.",
     "color": "#d4740e"},
    {"id": "seo-visual", "label": "Visual",
     "desc": "Screenshots, mobile testing, above-the-fold analysis, image SEO.",
     "color": "#c53030"},
    {"id": "seo-geo", "label": "GEO / AI",
     "desc": "AI crawler access, llms.txt, citability, brand-mention signals.",
     "color": "#db2777"},
    {"id": "seo-local", "label": "Local",
     "desc": "GBP signals, NAP consistency, reviews, local schema.",
     "color": "#16a34a"},
    {"id": "seo-maps", "label": "Maps",
     "desc": "Geo-grid rank tracking, GBP audit, competitor radius mapping.",
     "color": "#0ea5e9"},
    {"id": "seo-google", "label": "Google APIs",
     "desc": "CWV field data (CrUX), GSC indexation, GA4 organic traffic.",
     "color": "#fbbf24"},
    {"id": "seo-backlinks", "label": "Backlinks",
     "desc": "Referring domains, anchor text, toxic links, DA/PA.",
     "color": "#8b5cf6"},
    {"id": "seo-cluster", "label": "Cluster",
     "desc": "SERP-based semantic clustering for content architecture.",
     "color": "#10b981"},
    {"id": "seo-sxo", "label": "SXO",
     "desc": "Search Experience Optimization, page-type mismatch, persona scoring.",
     "color": "#f97316"},
    {"id": "seo-drift", "label": "Drift",
     "desc": "Baseline comparison, regression detection over time.",
     "color": "#6366f1"},
    {"id": "seo-ecommerce", "label": "E-commerce",
     "desc": "Product schema, marketplace intelligence.",
     "color": "#ef4444"},
    {"id": "seo-dataforseo", "label": "DataForSEO",
     "desc": "Live SERP, keyword, backlink data (paid extension).",
     "color": "#94a3b8"},
    {"id": "seo-image-gen", "label": "Image-Gen",
     "desc": "AI image generation for OG, blog, product, hero images (paid extension).",
     "color": "#64748b"},
    {"id": "seo-flow", "label": "FLOW",
     "desc": "Find -> Leverage -> Optimize -> Win framework prompts.",
     "color": "#a16207"},
]
